[project]
name = "docai"
version = "0.1.0"
description = "One to document them all"
readme = "README.md"
requires-python = ">=3.15"
dependencies = []

[project.scripts]
docai = "docai.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/docai"]
