providers:
  google:
    api_key_env: GEMINI_API_KEY

models:
  gemini-2.5-flash:
    default-provider: google
    model_name: gemini-2.5-flash
    # generation:
    #   temperature: 0.2
    #   max_output_tokens: 2048
    #   top_p: 0.95
  gemini-1.5-pro:
    default-provider: google
    model_name: gemini-1.5-pro
    generation:
      temperature: 0.4
      max_output_tokens: 4096

profiles:
  default:
    model: gemini-2.5-flash
    tools:
      allowed: [dummy_schedule_meeting_function]
  fallback:
    model: gemini-2.5-flash
    provider: google # provider can be set if the wanted provider is different from the default provider
    tools:
      allowed: [search]
  fast:
    model: gemini-2.5-flash
    tools:
      allowed: [search]

# Optional global tool definitions if you need config per tool
# tools:
#   search:
#     type: web
#     timeout_ms: 5000
#   code_interpreter:
#     type: python_sandbox
#     timeout_ms: 20000

globals:
  max_concurrency: 10
