providers:
  google:
    api_key_env: GEMINI_API_KEY
    # api_key: xxxxxx # can be set if the api key should not be stored in an environment variable # can also be set as an command line argument

models:
  gemini-2.5-flash:
    model_name: gemini-2.5-flash
    # generation:
    #   temperature: 0.2
    #   max_output_tokens: 2048
    #   top_p: 0.95
  gemini-1.5-pro:
    model_name: gemini-1.5-pro
    generation:
      temperature: 0.4
      max_output_tokens: 4096

profiles:
  default: # will be used as the default profile if no profile is specified
    provider: google
    model: gemini-2.5-flash
  fallback: # will be used as the fallback profile if no fallback profile is specified
    provider: google
    model: gemini-2.5-flash
  fast:
    provider: google
    model: gemini-2.5-flash

globals:
  max_concurrency: 10 # if not specified, the default value is 1
  max_retries: 5
  retry_delay: 5000 # in ms
