# logging_base.yaml
version: 1

disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  brief:
    format: "%(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    level: DEBUG
    filename: /tmp/docai.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf-8

loggers:
  docai_project: # The main logger for your application
    level: INFO # Capture all messages here
    handlers: [console] # Only the console by default
    propagate: False

root:
  level: WARNING
  handlers: [console] # The default for anything not covered above
